{% set version = "134455" %}

package:
  name: functorch
  version: {{ version }}

source:
  # This is a dummy package and has been included into pytorch itself
  # https://github.com/pytorch/functorch/releases/tag/v1.13.0
  # we use the pytorch/pytorch archive because 
  # they publish wheels for each pytorch version, but not on their repo
  # https://pypi.org/project/functorch/#history
  url: https://github.com/pytorch/pytorch/archive/{{ version }}.tar.gz
  sha256: ed67ff04fe76988350c7aed312db5397440ab7bf9c1146ff4534a218a63db931
build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pytorch >={{ version }}
  run:
    - python >=3.7
    - pytorch >={{ version }}

test:
  requires:
    - pip
  imports:
    - functorch
  commands:
    - pip check


about:
  home: https://github.com/pytorch/functorch
  summary: functorch is JAX-like composable function transforms for PyTorch
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
