{% set version = "1.13.0" %}

 package:
   name: functorch
   version: {{ version }}

 source:
   url: https://github.com/pytorch/functorch/archive/v{{ version }}.tar.gz
   sha256: f4788e3d25f25e89aee90f8e9a4eb09ed51c55553b27a6e85c894743d90a600c

build:
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python
    - pytorch
  run:
    - python
    - pytorch

test:
  source_files:
    - test
  requires:
    - pip
    - pytest
    - expecttest
    - pyyaml
  imports:
    - functorch
  commands:
    - pip check
    # adding two tests from readme besides the sanity check in run_test.py
    - pytest test/test_vmap.py -v
    - pytest test/test_eager_transforms.py -v

about:
  home: https://github.com/pytorch/functorch
  summary: functorch is JAX-like composable function transforms for PyTorch
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
