{% set version = "1.13.1" %}

package:
  name: functorch
  version: {{ version }}

source:
  # This is a dummy package and has been included into pytorch itself
  # https://github.com/pytorch/functorch/releases/tag/v1.13.0
  # we use the pytorch/pytorch archive because 
  # they publish wheels for each pytorch version, but not on their repo
  # https://pypi.org/project/functorch/#history
  url: https://github.com/pytorch/pytorch/archive/v{{ version }}.tar.gz
  sha256: f4788e3d25f25e89aee90f8e9a4eb09ed51c55553b27a6e85c894743d90a600c

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pytorch {{ version }}
  run:
    - python >=3.7
    - pytorch {{ version }}

test:
  requires:
    - pip
  imports:
    - functorch
  commands:
    - pip check


about:
  home: https://github.com/pytorch/functorch
  summary: functorch is JAX-like composable function transforms for PyTorch
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ngam
